expected/modifications.out.tmpl
expected/queries.out
pg_shard.c
sql/queries.sql

Hey @jasonmp85 ,
* For subqueries we need to make two checks, which we discussed earlier:
1. One for queryTree->hasSubLinks == true
2. One for rangeTableEntry->rtekind == RTE_SUBQUERY
* For the common table expressions, I added a new check. In the query struct, there is a queryTree->cteList field. Wherever a CTE exits in a query (SELECT,FROM or WHERE), the field is updated.
* Since we do not support CTEs at all, it is OK to check that variable. Also, it becomes unnecessary to check it in range table entries iteration.
* I think we also need to disccuss functions. For the functions which appears in SELECT or WHERE clause, we can plan the query and get correct results (as far as I observed).
* However, for the functions which appears in FROM clause, we fail to plan and execute the query. …

Improve unsupported feature identification - Subqueries, CTEs and Functions

---

expected/queries.out
pg_shard.c
sql/queries.sql

Reworks multi-shard SELECT so instead of performing quals both remotely and on the local sequential scan, they are only performed remotely. This frees us up to avoid pulling columns mentioned only in quals over the wire, which provides users more control over how much data gets pulled in a multi-shard query.
fixes #33

Fix multi-shard SELECT to pull only needed columns

---

prune_shard_list.c
prune_shard_list.h

This branch implements a cache in front of  *GetOperatorByType* function, so that it prevents unnecessary calls to *GetDefaultOpClass* function.
With this implementation, we get the same performance improvement that we observed with @ozgune. I may send the details of the results via an email.
fixes #50
Review tasks:

pg_shard performance improvement

---

expected/queries.out
pg_shard.c
sql/queries.sql

Because `Var`s from `HAVING` clauses weren't being included in the remote query's target list, they would be `NULL` if they did not appear in the target list or a `GROUP`/`ORDER` clause. This change includes them in the remote target list so they'll be available for local evaluation of the `HAVING` clause.
fixes #53

Fix multi-shard SELECT problem with HAVING clauses

---

create_shards.c
distribution_metadata.c
distribution_metadata.h
expected/create_shards.out.tmpl
prune_shard_list.c
prune_shard_list.h
sql/create_shards.sql.tmpl

This pull request aims to prevent tables to be distributed with columns that cannot be used as distribution column.
fixes #16
**Code Review Tasks**

Feature issue#16

---

expected/queries.out
pg_shard.c
sql/queries.sql

I added an `Assert` in a9564eb based on the assumption that if all shards are pruned, something is wrong. I neglected to think about any `SELECT` query with unsatisfiable restrictions. Such queries cause the `Assert` to fail.
That said, even without the `Assert`, the behavior is undesirable: we print _cannot execute select over multiple shards_, which is terribly misleading (especially since we _can_ do that).
This change updates names to be clearer that the multi-shard `SELECT` path is really just a possibility in execution and is actually valid for zero shards. I've added a unit test to verify that such zero-shard queries return the correct result (no rows).
Review tasks:

Handle zero-shard SELECT queries

---

Makefile
pg_shard--1.0--1.1.sql
pg_shard--1.1.sql
pg_shard.control

Adding a new UDF means adding an upgrade script to augment existing installations of pg_shard.
fixes #69

Bump default version; add upgrade script

---

pg_shard.c

This pull request aims to fix the memory leak created by the call to PostgreSQL's BuildTupleFromCStrings function. Temporary memory context is created for each call to BuildTupleFromCStrings and reseted after the call.
Fixes #77

Fix memory leak on large unbounded queries

---

Makefile

As reported [here][1], older versions of make don't support `else if`-like constructs, so we need to just use plain `if` statements or nest them if absolutely necessary.
Additionally, we were missing the logic to set `MAJORVERSION` based on `VERSION` if the former is not present. Older PostgreSQL versions need this, so I've added it.
Fixes #83.
[1]: https://groups.google.com/d/msg/pg_shard-users/N92qnf-Cj6A/lqPKw_9ekfUJ

Tweak Makefile version detection

---

Makefile

Other modules in contrib have a block like this. Because pg_shard uses libpq, it is listed as a prereq that needs to be built first (for an in-tree build this is important): postgres_fdw does the same.
See citusdata/postgres@2e335bd for how this is used.
Resolves #44

Add conditional to detect in-tree build

---

.uncrustify.cfg
connection.c
connection.h
create_shards.c
create_shards.h
distribution_metadata.c
distribution_metadata.h
extend_ddl_commands.c
generate_ddl_commands.c
pg_shard.c
pg_shard.h
prune_shard_list.c
prune_shard_list.h
repair_shards.c
ruleutils_93.c
ruleutils_94.c
test/create_shards.c
test/extend_ddl_commands.c
test/test_helper_functions.h

Works well with at least Uncrustify 0.61, though it may work just as well with other versions. In zsh one can check style with:
uncrustify -c .uncrustify.cfg --check  **/*.[ch]~ruleutils*
This'll exit with 0 if all files are compliant and will exit with 1 otherwise. Pass --no-backup instead of --check to have uncrustify modify all files in place to be compliant.
Deduced style from most of our codebase and style guides and consulted with team members for any ambiguities I needed resolved.

Add uncrustify config and use it

---

expected/citus_metadata_sync.out
pg_shard--1.0--1.1.sql
pg_shard--1.1.sql
sql/citus_metadata_sync.sql

A customer noticed this function could not be called more than once without error. Now calling it more than once has the same effect as calling it once. In addition, if a shard placement's state has changed since the most recent call, an additional call will update the placement state in CitusDB's view.
Added a unit test to verify these cases.
For an explanation of the algorithm in use here, read the _Bulk upsert with lock_ section in [this Stack Overflow answer](http://stackoverflow.com/a/17267423).
**Code review tasks**

Modify Citus metadata sync to be idempotent

---

expected/modifications.out.tmpl
pg_shard.c
sql/modifications.sql

This pull request prevents WHERE clause statements to have VOLATILE or MUTABLE functions.
Fixes #47
**Review tasks**

Bugfix volalite functions#47

---

create_shards.c
expected/create_shards.out.tmpl
sql/create_shards.sql.tmpl

Surprising that this conditional didn't already have an else clause, but so it goes. This causes us to reject any partition types we don't explicitly support (the function used to silently succeed).

Reject unknown partition types

---

CHANGELOG.md
META.json
expected/repair_shards.out.tmpl
repair_shards.c
sql/repair_shards.sql.tmpl

`list_union` was inappropriate here to begin with; furthermore, it needs the elements of each list to be Nodes. If they are not, we'll get an unsafe cast and (hopefully) an `ERROR`.
Do _not_ hit "merge" on this… the pull request is against `master` and so merging would create a new release. I need to bump the version number and squash the test/fix commits before merging.

Fix repair bug

---

expected/modifications.out
expected/queries.out
expected/queries_1.out
pg_shard.c
sql/modifications.sql

Found this when doing CitusDB integration. If CitusDB has created an e.g. range partition table I found it "just works" with pg_shard save one caveat: if no shard exists to receive an incoming row, our zero-shard SELECT logic kicked in and pg_shard would happily put the row into the local relation.
UPDATE and DELETE are safe to run locally as the local table should be empty to begin with, but INSERT is not: we should raise an error rather than continue with a zero-shard INSERT.

Throw error for zero-shard INSERTs

---

create_shards.c
distribution_metadata.c
expected/create_shards.out
expected/distribution_metadata.out
sql/distribution_metadata.sql

Discovered that system cache lookups have Asserts that fail if any name over `NAMEDATALEN` is provided. This change gives a nicer behavior than just crashing the whole backend.
I also discovered that `ResolveRelationId` silently truncates its input, which I initially thought I'd fix. It appears _many_ functions that use the [`name` data type](http://www.postgresql.org/docs/9.4/static/datatype-character.html#DATATYPE-CHARACTER-SPECIAL-TABLE) also silently truncate their input, so I left that as-is. At any rate, it accepts a qualified name (delimited by periods), so detecting whether any given part of that is too long is more trouble than it's worth, especially when other pieces of PostgreSQL proper truncate regardless.

Check column name length in ColumnNameToColumn

---

Makefile
distribution_metadata.c
test/distribution_metadata.c
test/fake_fdw.c

@anarazel asked for this in #121.
This warning isn't as useful as the other unused warnings (such as
unused variables) and it was getting to be more trouble than it was
worth. This removes it entirely and cuts out any extra source that
was previously needed to opt-in to unused parameters.

Disable unused parameter compiler warning

---

ddl_commands.h
distribution_metadata.c
distribution_metadata.h
extend_ddl_commands.c
prune_shard_list.c
test/distribution_metadata.c

PostgreSQL doesn't have unsigned types, so using them when storing a value in a table doesn't make sense.

Switch to signed integers for all identifiers

---

expected/queries.out
expected/queries_1.out
pg_shard.c
sql/queries.sql

When a user attempts to interact with a `pg_shard`-distributed table using bare SQL in PL/pgSQL, they receive a confusing error message of _unrecognized node type: 2100_. We've had several users raise this issue and it's certainly possible additional customers just think PL/pgSQL support is broken entirely and haven't said anything.
The underlying issue is that PL/pgSQL caches plans for all static SQL appearing within functions. `pg_shard` uses a "custom" plan type (just an integer tag well above those used by PostgreSQL) so the caching methods fail. In the normal course of things we intercept e.g. `PREPARE` statements to keep users from caching plans, but PL/pgSQL bypasses that path and uses SPI's caching machinery directly.
I looked briefly into cramming the distributed plan into some …

Clarify confusing PL/pgSQL error message

---

.travis.yml
citus_metadata_sync.c
citus_metadata_sync.h
distribution_metadata.c
distribution_metadata.h
expected/citus_metadata_sync.out
expected/distribution_metadata.out
expected/init.out
expected/modifications.out
expected/queries.out
expected/queries_1.out
pg_shard--1.1--1.2.sql
pg_shard--1.2.sql
pg_shard.c
prune_shard_list.c
prune_shard_list.h
sql/citus_metadata_sync.sql
sql/distribution_metadata.sql
sql/init.sql
sql/modifications.sql
sql/queries.sql
test/distribution_metadata.c

OK, so this has been entirely rebased on top of the changes from #110, i.e. we're using SPI everywhere now. This review is now all about the triggers and views needed to adapt CitusDB's metadata tables to be used within `pg_shard`.
Travis is building this under PostgreSQL 9.3/9.4, and CitusDB 4.0, so there is some assurance this actually works.
**Code Review Tasks**
Resolves #11.
Resolves #27.

CitusDB metadata interoperability

---

include/distribution_metadata.h
src/create_shards.c
src/distribution_metadata.c
src/pg_shard.c
src/repair_shards.c
test/src/distribution_metadata.c

The guiding principle here is that readers must know about a relevant set of objects to perform distributed queries so need guarantees that the relevant set will not change beneath them during said queries.
In practice, this means we need two locks: one for the set of shards related to a relation and one for the set of placements related to a shard. If the caller intends to add shards (or (active) placements), they must hold an exclusive lock on the grouping relation (or shard). If the caller just wants to act on the current set of shards (or the (active) placements), they need a shared lock before reading.
I explored using row locks to accomplish this but they'd be just as arbitrary as some advisory lock with the added downside that they can cause disk writes. `LockDatabaseObject` …

Lock metadata during cluster structural changes

---

doc/README.md

Some of our customers have mistakenly created clusters where they swap their intended shard count and replication factor. PostgreSQL lets name parameters in function calls, so might as well make use of that in our documentation for clarity's sake.

Name parameters in the README usage examples

---

include/connection.h
src/create_shards.c
test/launcher.sh

CitusDB allows lines in `pg_worker_list.conf` to omit the port number, whereas `pg_shard` required it: confusing (or annoying) users of both.
This changes the `sscanf` format string to parse both the node name and node port as strings. If no node port is specified (or if that token starts with `#` i.e. begins a line comment), the default port is used; otherwise, we parse the node port string into an integer in precisely the same fashion used by CitusDB.
The reviewer of this request should consult the CitusDB functions `LoadWorkerNodeList` and `ParseWorkerNodeLine` in `worker_node_manager.c` to verify that the `pg_shard` implementation faithfully emulates CitusDB's implementation. Note that CitusDB uses functions from `hba.c` that are inaccessible to `pg_shard`, which is why the …

Use master's port if worker port config absent

---

include/pg_shard.h
src/pg_shard.c
test/expected/00-init.out
test/sql/00-init.sql

The `use_citusdb_select_logic` configuration parameter defaults false, which is causing confusion now that pg_shard sees and understands all CitusDB metadata. This detects CitusDB at build time and defaults the configuration to true when pg_shard is built against CitusDB.
Resolves #132

Use CitusDB SELECT logic by default within CitusDB

---

include/create_shards.h
src/create_shards.c
test/expected/05-create_shards.out
test/expected/09-queries.out
test/expected/09-queries_1.out
test/sql/05-create_shards.sql

There are `2^32` distinct "hash tokens" in our hash space, but we were using `INT32_MAX (2^32 - 1)` in the code instead. Because of this, shard counts which one might expect to divide evenly into the space (such as 16, 32, or 256) had fewer tokens than they should have. The remainder of the tokens were stuffed into the last shard, causing uneven load.
This fixes that by defining a 64-bit constant equal to `2^32` and then using that to calculate the distance between shards in the hash space.
Unlike #145, in "weird" shard counts, the first `n-1` shards will have one size and the final shard will have _all_ leftover tokens. This means the final shard could contain up to `n-1` more hash tokens than the other shards, which might have load implications. In #145, all shards are within one token …

Fix hash token distribution algorithm

---

Makefile

On redhat/fedora, the regression tests fail due to the order of their execution. We haven't tried to figure out exactly why this happens, but on Redhat / Fedora, tests are executed out-of-order as follows:
```bash
/usr/local/pgsql/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --psqldir='/usr/local/pgsql/bin'    --inputdir=test --load-language=plpgsql --launcher=./test/launcher.sh  --dbname=contrib_regression 02-distribution_metadata 04-generate_ddl_commands 13-data_types 05-create_shards 11-citus_metadata_sync 03-extend_ddl_commands 10-utilities 09-queries 12-create_insert_proxy 07-repair_shards 01-connection 06-prune_shard_list 00-init 08-modifications
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" …
```

Makefile is updated to fix regression test failures on Redhat / Fedora

---

src/pg_shard.c

We slightly changed DTM interface and now it should be called in following way:
```sql
SELECT dtm_begin_transaction(); -- Run on node1, returns int, for example 42
SELECT dtm_join_transaction(42); -- Run on node2
-- Now we can start usual transactions, snapshot will be set automatically for both nodes.
(COMMIT; COMMIT) -- commit as usual should be done in parallel
```
Also I've added PrepareDtmTransaction to distributed selects too, so now we can have consistent read transactions too.

Transaction manager integration

---

test/expected/12-create_insert_proxy.out
test/sql/12-create_insert_proxy.sql

The output changes slightly in 9.5, so we'll just squelch the output to avoid having to make a 9.5-specific test file.

Squelch PL/pgSQL context in test

---

CHANGELOG.md
META.json
src/distribution_metadata.c

Version v1.2 introduced the use of SPI in the metadata system to better abstract differences between pg_shard and CitusDB representations of distribution metadata. We didn't initially use cached SPI plans because cursory tests showed limited wins given the added complexity.
Well, additional tests uncovered _severe_ performance regressions when many writers are involved. This change caches each metadata function's SPI plan in a function-local static variable on first execution, using the cached plans on subsequent executions. After this change, we can restore performance to near v1.1 levels (SPI does inevitably add _some_ overhead, no matter what).

Cache SPI plans to restore performance
